wandb_version: 1

attention_sparsity_factor:
  value: 5
batch_size:
  value: 64
dropout:
  value: 0.3
expanded_dim:
  value: 1
hidden_dim:
  value: 64
kernel_size:
  value: 2
lr:
  value: 0.0679114561861929
max_delta:
  value: 2
max_gradient_norm:
  value: 100
num_heads:
  value: 2
num_layers:
  value: 3
patch_len:
  value: 32
ssm_conv:
  value: 2
ssm_rank:
  value: 8
stat_size:
  value: 64
stride:
  value: 8
transformer_layers:
  value: 4
