wandb_version: 1

attention_sparsity_factor:
  value: 3
batch_size:
  value: 128
dropout:
  value: 0.5
expanded_dim:
  value: 2
hidden_dim:
  value: 64
kernel_size:
  value: 11
lr:
  value: 0.02976721506724516
max_delta:
  value: 5
max_gradient_norm:
  value: 100
num_heads:
  value: 4
num_layers:
  value: 3
patch_len:
  value: 8
ssm_conv:
  value: 16
ssm_rank:
  value: 16
stat_size:
  value: 16
stride:
  value: 4
transformer_layers:
  value: 4
