wandb_version: 1

attention_sparsity_factor:
  value: 6
batch_size:
  value: 64
dropout:
  value: 0.3
expanded_dim:
  value: 8
hidden_dim:
  value: 64
kernel_size:
  value: 11
lr:
  value: 0.05022291581277842
max_delta:
  value: 5
max_gradient_norm:
  value: 1
num_heads:
  value: 4
num_layers:
  value: 5
patch_len:
  value: 24
ssm_conv:
  value: 84
ssm_rank:
  value: 32
stat_size:
  value: 64
stride:
  value: 8
transformer_layers:
  value: 4
