wandb_version: 1

attention_sparsity_factor:
  value: 4
batch_size:
  value: 64
dropout:
  value: 0.3
expanded_dim:
  value: 2
hidden_dim:
  value: 64
kernel_size:
  value: 9
lr:
  value: 0.0007474856498365771
max_delta:
  value: 5
max_gradient_norm:
  value: 0.01
num_heads:
  value: 1
num_layers:
  value: 5
patch_len:
  value: 8
ssm_conv:
  value: 16
ssm_rank:
  value: 8
stat_size:
  value: 64
stride:
  value: 1
transformer_layers:
  value: 5
