wandb_version: 1

attention_sparsity_factor:
  value: 6
batch_size:
  value: 128
dropout:
  value: 0.3
expanded_dim:
  value: 2
hidden_dim:
  value: 64
kernel_size:
  value: 5
lr:
  value: 0.0459689222508671
max_delta:
  value: 1
max_gradient_norm:
  value: 100
num_heads:
  value: 1
num_layers:
  value: 6
patch_len:
  value: 32
ssm_conv:
  value: 2
ssm_rank:
  value: 32
stat_size:
  value: 32
stride:
  value: 1
transformer_layers:
  value: 3
