wandb_version: 1

attention_sparsity_factor:
  value: 4
batch_size:
  value: 64
dropout:
  value: 0.3
expanded_dim:
  value: 8
hidden_dim:
  value: 128
kernel_size:
  value: 9
lr:
  value: 0.04985337733445902
max_delta:
  value: 3
max_gradient_norm:
  value: 100
num_heads:
  value: 1
num_layers:
  value: 3
patch_len:
  value: 24
ssm_conv:
  value: 32
ssm_rank:
  value: 16
stat_size:
  value: 16
stride:
  value: 1
transformer_layers:
  value: 6
