wandb_version: 1

attention_sparsity_factor:
  value: 6
batch_size:
  value: 128
dropout:
  value: 0.5
expanded_dim:
  value: 1
hidden_dim:
  value: 256
kernel_size:
  value: 11
lr:
  value: 0.026804058751422853
max_delta:
  value: 5
max_gradient_norm:
  value: 1
num_heads:
  value: 2
num_layers:
  value: 2
patch_len:
  value: 16
ssm_conv:
  value: 2
ssm_rank:
  value: 8
stat_size:
  value: 64
stride:
  value: 4
transformer_layers:
  value: 5
