wandb_version: 1

attention_sparsity_factor:
  value: 6
batch_size:
  value: 64
dropout:
  value: 0.3
expanded_dim:
  value: 4
hidden_dim:
  value: 64
kernel_size:
  value: 3
lr:
  value: 0.024303289297094497
max_delta:
  value: 5
max_gradient_norm:
  value: 100
num_heads:
  value: 2
num_layers:
  value: 5
patch_len:
  value: 24
ssm_conv:
  value: 8
ssm_rank:
  value: 8
stat_size:
  value: 16
stride:
  value: 1
transformer_layers:
  value: 6
