wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.3
hidden_dim:
  value: 128
lr:
  value: 0.001
max_gradient_norm:
  value: 1
num_heads:
  value: 2
patch_len:
  value: 16
stride:
  value: 8
