wandb_version: 1

attention_sparsity_factor:
  value: 6
batch_size:
  value: 64
dropout:
  value: 0.5
expanded_dim:
  value: 2
hidden_dim:
  value: 128
kernel_size:
  value: 2
lr:
  value: 0.07544397691014225
max_delta:
  value: 2
max_gradient_norm:
  value: 1
num_heads:
  value: 1
num_layers:
  value: 6
patch_len:
  value: 8
ssm_conv:
  value: 8
ssm_rank:
  value: 32
stat_size:
  value: 16
stride:
  value: 16
transformer_layers:
  value: 4
