wandb_version: 1

attention_sparsity_factor:
  value: 6
batch_size:
  value: 64
dropout:
  value: 0.5
expanded_dim:
  value: 2
hidden_dim:
  value: 128
kernel_size:
  value: 5
lr:
  value: 0.03510345681738869
max_delta:
  value: 3
max_gradient_norm:
  value: 0.01
num_heads:
  value: 4
num_layers:
  value: 5
patch_len:
  value: 16
ssm_conv:
  value: 84
ssm_rank:
  value: 8
stat_size:
  value: 32
stride:
  value: 4
transformer_layers:
  value: 6
