wandb_version: 1

attention_sparsity_factor:
  value: 5
batch_size:
  value: 64
dropout:
  value: 0.4
expanded_dim:
  value: 2
hidden_dim:
  value: 256
kernel_size:
  value: 7
lr:
  value: 0.037051662390176224
max_delta:
  value: 3
max_gradient_norm:
  value: 100
num_heads:
  value: 4
num_layers:
  value: 3
patch_len:
  value: 16
ssm_conv:
  value: 8
ssm_rank:
  value: 32
stat_size:
  value: 16
stride:
  value: 16
transformer_layers:
  value: 5
