wandb_version: 1

attention_sparsity_factor:
  value: 2
batch_size:
  value: 128
dropout:
  value: 0.5
expanded_dim:
  value: 8
hidden_dim:
  value: 64
kernel_size:
  value: 9
lr:
  value: 0.06714496226222195
max_delta:
  value: 4
max_gradient_norm:
  value: 1
num_heads:
  value: 4
num_layers:
  value: 6
patch_len:
  value: 32
ssm_conv:
  value: 84
ssm_rank:
  value: 16
stat_size:
  value: 16
stride:
  value: 4
transformer_layers:
  value: 4
