wandb_version: 1

attention_sparsity_factor:
  value: 5
batch_size:
  value: 64
dropout:
  value: 0.4
expanded_dim:
  value: 4
hidden_dim:
  value: 64
kernel_size:
  value: 11
lr:
  value: 0.001
max_delta:
  value: 5
max_gradient_norm:
  value: 1
num_heads:
  value: 4
num_layers:
  value: 6
patch_len:
  value: 68
ssm_conv:
  value: 32
ssm_rank:
  value: 16
stat_size:
  value: 64
transformer_layers:
  value: 3
