wandb_version: 1

attention_sparsity_factor:
  value: 4
batch_size:
  value: 64
dropout:
  value: 0.5
expanded_dim:
  value: 4
hidden_dim:
  value: 128
kernel_size:
  value: 7
lr:
  value: 0.001
max_gradient_norm:
  value: 100
num_heads:
  value: 4
patch_len:
  value: 16
ssm_conv:
  value: 16
ssm_dt_rank:
  value: 16
ssm_rank:
  value: 32
stat_size:
  value: 16
stride:
  value: 4
transformer_layers:
  value: 5
