wandb_version: 1

attention_sparsity_factor:
  value: 5
batch_size:
  value: 64
dropout:
  value: 0.5
expanded_dim:
  value: 4
hidden_dim:
  value: 128
kernel_size:
  value: 11
lr:
  value: 0.001
max_gradient_norm:
  value: 1
num_heads:
  value: 1
patch_len:
  value: 8
ssm_conv:
  value: 16
ssm_dt_rank:
  value: 8
ssm_rank:
  value: 16
stat_size:
  value: 64
stride:
  value: 1
transformer_layers:
  value: 2
