wandb_version: 1

attention_sparsity_factor:
  value: 5
batch_size:
  value: 64
dropout:
  value: 0.3
expanded_dim:
  value: 1
hidden_dim:
  value: 128
kernel_size:
  value: 5
lr:
  value: 0.001
max_gradient_norm:
  value: 100
num_heads:
  value: 2
patch_len:
  value: 16
ssm_conv:
  value: 16
ssm_dt_rank:
  value: 8
ssm_rank:
  value: 8
stat_size:
  value: 16
stride:
  value: 8
transformer_layers:
  value: 5
