wandb_version: 1

attention_sparsity_factor:
  value: 2
batch_size:
  value: 128
dropout:
  value: 0.5
expanded_dim:
  value: 1
hidden_dim:
  value: 64
kernel_size:
  value: 3
lr:
  value: 0.001
max_gradient_norm:
  value: 0.01
num_heads:
  value: 2
patch_len:
  value: 8
ssm_conv:
  value: 8
ssm_dt_rank:
  value: 16
ssm_rank:
  value: 16
stat_size:
  value: 64
stride:
  value: 4
transformer_layers:
  value: 4
