wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.3
hidden_dim:
  value: 64
kernel_size:
  value: 7
lr:
  value: 0.001
max_gradient_norm:
  value: 0.01
num_heads:
  value: 2
patch_len:
  value: 32
stride:
  value: 1
transformer_layers:
  value: 6
