wandb_version: 1

attention_sparsity_factor:
  value: 4
batch_size:
  value: 128
dropout:
  value: 0.4
expanded_dim:
  value: 2
hidden_dim:
  value: 256
kernel_size:
  value: 9
lr:
  value: 0.03654444410526605
max_delta:
  value: 1
max_gradient_norm:
  value: 0.01
num_heads:
  value: 1
num_layers:
  value: 3
patch_len:
  value: 16
ssm_conv:
  value: 2
ssm_rank:
  value: 8
stat_size:
  value: 64
stride:
  value: 4
transformer_layers:
  value: 4
