wandb_version: 1

attention_sparsity_factor:
  value: 4
batch_size:
  value: 128
dropout:
  value: 0.4
expanded_dim:
  value: 2
hidden_dim:
  value: 128
kernel_size:
  value: 2
lr:
  value: 0.026961369082571823
max_delta:
  value: 3
max_gradient_norm:
  value: 100
num_heads:
  value: 2
num_layers:
  value: 6
patch_len:
  value: 8
ssm_conv:
  value: 8
ssm_rank:
  value: 16
stat_size:
  value: 32
stride:
  value: 1
transformer_layers:
  value: 3
