wandb_version: 1

attention_sparsity_factor:
  value: 6
batch_size:
  value: 64
dropout:
  value: 0.4
expanded_dim:
  value: 2
hidden_dim:
  value: 128
kernel_size:
  value: 3
lr:
  value: 0.02415666247921692
max_delta:
  value: 4
max_gradient_norm:
  value: 100
num_heads:
  value: 2
num_layers:
  value: 6
patch_len:
  value: 32
ssm_conv:
  value: 84
ssm_rank:
  value: 8
stat_size:
  value: 16
stride:
  value: 8
transformer_layers:
  value: 2
