wandb_version: 1

attention_sparsity_factor:
  value: 4
batch_size:
  value: 128
dropout:
  value: 0.5
expanded_dim:
  value: 1
hidden_dim:
  value: 128
kernel_size:
  value: 3
lr:
  value: 0.05405783323573361
max_delta:
  value: 5
max_gradient_norm:
  value: 100
num_heads:
  value: 4
num_layers:
  value: 2
patch_len:
  value: 8
ssm_conv:
  value: 8
ssm_rank:
  value: 32
stat_size:
  value: 64
stride:
  value: 4
transformer_layers:
  value: 3
