wandb_version: 1

attention_sparsity_factor:
  value: 2
batch_size:
  value: 64
dropout:
  value: 0.3
expanded_dim:
  value: 1
hidden_dim:
  value: 128
kernel_size:
  value: 5
lr:
  value: 0.03801592441683808
max_delta:
  value: 4
max_gradient_norm:
  value: 0.01
num_heads:
  value: 1
num_layers:
  value: 2
patch_len:
  value: 16
ssm_conv:
  value: 16
ssm_rank:
  value: 32
stat_size:
  value: 32
stride:
  value: 4
transformer_layers:
  value: 6
