wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.5
hidden_dim:
  value: 128
lr:
  value: 0.001
max_gradient_norm:
  value: 100
num_heads:
  value: 1
patch_len:
  value: 32
stride:
  value: 4
transformer_layers:
  value: 5
