wandb_version: 1

attention_sparsity_factor:
  value: 3
batch_size:
  value: 128
dropout:
  value: 0.3
expanded_dim:
  value: 4
hidden_dim:
  value: 128
kernel_size:
  value: 9
lr:
  value: 0.001
max_delta:
  value: 1
max_gradient_norm:
  value: 0.01
num_heads:
  value: 4
patch_len:
  value: 32
ssm_conv:
  value: 8
ssm_rank:
  value: 8
stat_size:
  value: 64
stride:
  value: 4
transformer_layers:
  value: 5
