wandb_version: 1

attention_sparsity_factor:
  value: 6
batch_size:
  value: 128
dropout:
  value: 0.5
expanded_dim:
  value: 1
hidden_dim:
  value: 256
kernel_size:
  value: 3
lr:
  value: 0.031062886351670912
max_delta:
  value: 1
max_gradient_norm:
  value: 100
num_heads:
  value: 1
num_layers:
  value: 3
patch_len:
  value: 8
ssm_conv:
  value: 84
ssm_rank:
  value: 8
stat_size:
  value: 16
stride:
  value: 8
transformer_layers:
  value: 5
