wandb_version: 1

attention_sparsity_factor:
  value: 2
batch_size:
  value: 64
dropout:
  value: 0.3
expanded_dim:
  value: 8
hidden_dim:
  value: 128
kernel_size:
  value: 11
lr:
  value: 0.07182456244324092
max_delta:
  value: 1
max_gradient_norm:
  value: 1
num_heads:
  value: 2
num_layers:
  value: 3
patch_len:
  value: 8
ssm_conv:
  value: 8
ssm_rank:
  value: 8
stat_size:
  value: 16
stride:
  value: 8
transformer_layers:
  value: 4
