wandb_version: 1

attention_sparsity_factor:
  value: 6
batch_size:
  value: 64
dropout:
  value: 0.4
expanded_dim:
  value: 1
hidden_dim:
  value: 128
kernel_size:
  value: 9
lr:
  value: 0.02193282116045489
max_delta:
  value: 2
max_gradient_norm:
  value: 100
num_heads:
  value: 4
num_layers:
  value: 5
patch_len:
  value: 32
ssm_conv:
  value: 84
ssm_rank:
  value: 8
stat_size:
  value: 32
stride:
  value: 4
transformer_layers:
  value: 2
