wandb_version: 1

attention_sparsity_factor:
  value: 4
batch_size:
  value: 64
dropout:
  value: 0.5
expanded_dim:
  value: 2
hidden_dim:
  value: 128
kernel_size:
  value: 3
lr:
  value: 0.052612046074146865
max_delta:
  value: 4
max_gradient_norm:
  value: 1
num_heads:
  value: 2
num_layers:
  value: 3
patch_len:
  value: 16
ssm_conv:
  value: 32
ssm_rank:
  value: 16
stat_size:
  value: 16
stride:
  value: 4
transformer_layers:
  value: 2
