wandb_version: 1

attention_sparsity_factor:
  value: 5
batch_size:
  value: 64
dropout:
  value: 0.4
expanded_dim:
  value: 1
hidden_dim:
  value: 64
kernel_size:
  value: 7
lr:
  value: 0.0525810535021272
max_delta:
  value: 1
max_gradient_norm:
  value: 1
num_heads:
  value: 2
num_layers:
  value: 2
patch_len:
  value: 32
ssm_conv:
  value: 84
ssm_rank:
  value: 16
stat_size:
  value: 32
stride:
  value: 1
transformer_layers:
  value: 3
