wandb_version: 1

attention_sparsity_factor:
  value: 5
batch_size:
  value: 128
dropout:
  value: 0.5
expanded_dim:
  value: 1
hidden_dim:
  value: 64
kernel_size:
  value: 3
lr:
  value: 0.07904664643675556
max_delta:
  value: 5
max_gradient_norm:
  value: 1
num_heads:
  value: 1
num_layers:
  value: 5
patch_len:
  value: 24
ssm_conv:
  value: 84
ssm_rank:
  value: 32
stat_size:
  value: 64
stride:
  value: 1
transformer_layers:
  value: 3
