wandb_version: 1

attention_sparsity_factor:
  value: 5
batch_size:
  value: 64
dropout:
  value: 0.3
expanded_dim:
  value: 4
hidden_dim:
  value: 256
kernel_size:
  value: 5
lr:
  value: 0.06232586925292713
max_delta:
  value: 2
max_gradient_norm:
  value: 1
num_heads:
  value: 4
num_layers:
  value: 5
patch_len:
  value: 8
ssm_conv:
  value: 2
ssm_rank:
  value: 16
stat_size:
  value: 32
stride:
  value: 1
transformer_layers:
  value: 4
