wandb_version: 1

attention_sparsity_factor:
  value: 3
batch_size:
  value: 64
dropout:
  value: 0.3
expanded_dim:
  value: 2
hidden_dim:
  value: 128
kernel_size:
  value: 2
lr:
  value: 0.023556858628970834
max_delta:
  value: 3
max_gradient_norm:
  value: 0.01
num_heads:
  value: 4
num_layers:
  value: 3
patch_len:
  value: 24
ssm_conv:
  value: 32
ssm_rank:
  value: 32
stat_size:
  value: 32
stride:
  value: 8
transformer_layers:
  value: 5
