wandb_version: 1

attention_sparsity_factor:
  value: 3
batch_size:
  value: 64
dropout:
  value: 0.4
expanded_dim:
  value: 4
hidden_dim:
  value: 128
kernel_size:
  value: 3
lr:
  value: 0.09199774705322544
max_delta:
  value: 5
max_gradient_norm:
  value: 1
num_heads:
  value: 1
num_layers:
  value: 6
patch_len:
  value: 32
ssm_conv:
  value: 32
ssm_rank:
  value: 32
stat_size:
  value: 32
stride:
  value: 8
transformer_layers:
  value: 3
