wandb_version: 1

attention_sparsity_factor:
  value: 4
batch_size:
  value: 64
dropout:
  value: 0.3
expanded_dim:
  value: 4
hidden_dim:
  value: 256
kernel_size:
  value: 2
lr:
  value: 0.06429521837856302
max_delta:
  value: 4
max_gradient_norm:
  value: 0.01
num_heads:
  value: 1
num_layers:
  value: 3
patch_len:
  value: 8
ssm_conv:
  value: 32
ssm_rank:
  value: 16
stat_size:
  value: 64
stride:
  value: 8
transformer_layers:
  value: 4
