wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.5
hidden_dim:
  value: 64
kernel_size:
  value: 5
lr:
  value: 0.001
max_gradient_norm:
  value: 1
num_heads:
  value: 2
patch_len:
  value: 8
stride:
  value: 8
transformer_layers:
  value: 3
