wandb_version: 1

attention_sparsity_factor:
  value: 6
batch_size:
  value: 64
dropout:
  value: 0.4
hidden_dim:
  value: 128
kernel_size:
  value: 9
lr:
  value: 0.001
max_gradient_norm:
  value: 1
num_heads:
  value: 1
patch_len:
  value: 8
stride:
  value: 8
transformer_layers:
  value: 3
