wandb_version: 1

attention_sparsity_factor:
  value: 5
batch_size:
  value: 64
dropout:
  value: 0.4
hidden_dim:
  value: 64
kernel_size:
  value: 2
lr:
  value: 0.001
max_gradient_norm:
  value: 0.01
num_heads:
  value: 2
patch_len:
  value: 32
stride:
  value: 4
transformer_layers:
  value: 6
