wandb_version: 1

attention_sparsity_factor:
  value: 3
batch_size:
  value: 128
dropout:
  value: 0.5
hidden_dim:
  value: 128
kernel_size:
  value: 7
lr:
  value: 0.001
max_gradient_norm:
  value: 100
num_heads:
  value: 2
patch_len:
  value: 16
stride:
  value: 4
transformer_layers:
  value: 3
