wandb_version: 1

attention_sparsity_factor:
  value: 3
batch_size:
  value: 64
dropout:
  value: 0.3
expanded_dim:
  value: 4
hidden_dim:
  value: 64
kernel_size:
  value: 11
lr:
  value: 0.001
max_delta:
  value: 4
max_gradient_norm:
  value: 0.01
num_heads:
  value: 4
num_layers:
  value: 2
patch_len:
  value: 8
ssm_conv:
  value: 32
ssm_rank:
  value: 8
stat_size:
  value: 32
stride:
  value: 8
transformer_layers:
  value: 6
