wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.5
hidden_dim:
  value: 128
kernel_size:
  value: 9
lr:
  value: 0.001
max_gradient_norm:
  value: 1
num_heads:
  value: 2
patch_len:
  value: 8
stride:
  value: 4
transformer_layers:
  value: 3
