wandb_version: 1

attention_sparsity_factor:
  value: 4
batch_size:
  value: 64
dropout:
  value: 0.4
expanded_dim:
  value: 1
hidden_dim:
  value: 256
kernel_size:
  value: 9
lr:
  value: 0.0008298436153772682
max_delta:
  value: 2
max_gradient_norm:
  value: 100
num_heads:
  value: 2
num_layers:
  value: 2
patch_len:
  value: 24
ssm_conv:
  value: 2
ssm_rank:
  value: 16
stat_size:
  value: 32
stride:
  value: 1
transformer_layers:
  value: 6
