wandb_version: 1

attention_sparsity_factor:
  value: 3
batch_size:
  value: 64
dropout:
  value: 0.3
expanded_dim:
  value: 1
hidden_dim:
  value: 128
kernel_size:
  value: 9
lr:
  value: 0.001
max_delta:
  value: 1
max_gradient_norm:
  value: 100
num_heads:
  value: 1
num_layers:
  value: 2
patch_len:
  value: 16
ssm_conv:
  value: 2
ssm_rank:
  value: 32
stat_size:
  value: 16
transformer_layers:
  value: 6
