wandb_version: 1

attention_sparsity_factor:
  value: 5
batch_size:
  value: 64
dropout:
  value: 0.5
expanded_dim:
  value: 8
hidden_dim:
  value: 64
kernel_size:
  value: 11
lr:
  value: 0.001
max_delta:
  value: 2
max_gradient_norm:
  value: 1
num_heads:
  value: 1
patch_len:
  value: 8
ssm_conv:
  value: 2
ssm_rank:
  value: 16
stat_size:
  value: 16
stride:
  value: 1
transformer_layers:
  value: 3
