wandb_version: 1

attention_sparsity_factor:
  value: 2
batch_size:
  value: 128
dropout:
  value: 0.5
expanded_dim:
  value: 1
hidden_dim:
  value: 256
kernel_size:
  value: 2
lr:
  value: 0.04094445139778967
max_delta:
  value: 3
max_gradient_norm:
  value: 100
num_heads:
  value: 2
num_layers:
  value: 2
patch_len:
  value: 16
ssm_conv:
  value: 16
ssm_rank:
  value: 8
stat_size:
  value: 64
stride:
  value: 16
transformer_layers:
  value: 2
