wandb_version: 1

attention_sparsity_factor:
  value: 4
batch_size:
  value: 64
dropout:
  value: 0.3
expanded_dim:
  value: 4
hidden_dim:
  value: 128
kernel_size:
  value: 2
lr:
  value: 0.001
max_delta:
  value: 2
max_gradient_norm:
  value: 1
num_heads:
  value: 4
patch_len:
  value: 16
ssm_conv:
  value: 8
ssm_rank:
  value: 8
stat_size:
  value: 32
stride:
  value: 4
transformer_layers:
  value: 3
