wandb_version: 1

attention_sparsity_factor:
  value: 6
batch_size:
  value: 128
dropout:
  value: 0.4
expanded_dim:
  value: 8
hidden_dim:
  value: 64
kernel_size:
  value: 5
lr:
  value: 0.09630191173717904
max_delta:
  value: 1
max_gradient_norm:
  value: 0.01
num_heads:
  value: 4
num_layers:
  value: 3
patch_len:
  value: 16
ssm_conv:
  value: 32
ssm_rank:
  value: 16
stat_size:
  value: 32
stride:
  value: 8
transformer_layers:
  value: 4
