wandb_version: 1

attention_sparsity_factor:
  value: 6
batch_size:
  value: 64
dropout:
  value: 0.4
expanded_dim:
  value: 1
hidden_dim:
  value: 64
kernel_size:
  value: 3
lr:
  value: 0.03121107961247569
max_delta:
  value: 1
max_gradient_norm:
  value: 100
num_heads:
  value: 1
num_layers:
  value: 3
patch_len:
  value: 16
ssm_conv:
  value: 16
ssm_rank:
  value: 16
stat_size:
  value: 32
stride:
  value: 1
transformer_layers:
  value: 5
