wandb_version: 1

attention_sparsity_factor:
  value: 6
batch_size:
  value: 64
dropout:
  value: 0.5
expanded_dim:
  value: 8
hidden_dim:
  value: 256
kernel_size:
  value: 3
lr:
  value: 0.038643094174732454
max_delta:
  value: 4
max_gradient_norm:
  value: 1
num_heads:
  value: 1
num_layers:
  value: 6
patch_len:
  value: 16
ssm_conv:
  value: 84
ssm_rank:
  value: 16
stat_size:
  value: 64
stride:
  value: 1
transformer_layers:
  value: 6
