wandb_version: 1

attention_sparsity_factor:
  value: 5
batch_size:
  value: 128
dropout:
  value: 0.5
expanded_dim:
  value: 8
hidden_dim:
  value: 256
kernel_size:
  value: 9
lr:
  value: 0.01086540390221463
max_delta:
  value: 1
max_gradient_norm:
  value: 1
num_heads:
  value: 1
num_layers:
  value: 3
patch_len:
  value: 24
ssm_conv:
  value: 84
ssm_rank:
  value: 32
stat_size:
  value: 64
stride:
  value: 8
transformer_layers:
  value: 2
