wandb_version: 1

attention_sparsity_factor:
  value: 5
batch_size:
  value: 128
dropout:
  value: 0.5
expanded_dim:
  value: 1
hidden_dim:
  value: 128
kernel_size:
  value: 2
lr:
  value: 0.07982374487233937
max_delta:
  value: 5
max_gradient_norm:
  value: 100
num_heads:
  value: 1
num_layers:
  value: 3
patch_len:
  value: 24
ssm_conv:
  value: 8
ssm_rank:
  value: 8
stat_size:
  value: 16
stride:
  value: 1
transformer_layers:
  value: 2
