wandb_version: 1

attention_sparsity_factor:
  value: 2
batch_size:
  value: 128
dropout:
  value: 0.3
expanded_dim:
  value: 4
hidden_dim:
  value: 128
kernel_size:
  value: 7
lr:
  value: 0.0007213474141106201
max_delta:
  value: 4
max_gradient_norm:
  value: 0.01
num_heads:
  value: 2
num_layers:
  value: 2
patch_len:
  value: 8
ssm_conv:
  value: 16
ssm_rank:
  value: 8
stat_size:
  value: 16
stride:
  value: 4
transformer_layers:
  value: 3
