wandb_version: 1

attention_sparsity_factor:
  value: 2
batch_size:
  value: 128
dropout:
  value: 0.5
expanded_dim:
  value: 2
hidden_dim:
  value: 64
kernel_size:
  value: 9
lr:
  value: 0.06057344880290435
max_delta:
  value: 4
max_gradient_norm:
  value: 0.01
num_heads:
  value: 2
num_layers:
  value: 3
patch_len:
  value: 8
ssm_conv:
  value: 8
ssm_rank:
  value: 8
stat_size:
  value: 64
stride:
  value: 1
transformer_layers:
  value: 4
