wandb_version: 1

attention_sparsity_factor:
  value: 3
batch_size:
  value: 64
dropout:
  value: 0.4
expanded_dim:
  value: 2
hidden_dim:
  value: 64
kernel_size:
  value: 2
lr:
  value: 0.001
max_delta:
  value: 1
max_gradient_norm:
  value: 1
num_heads:
  value: 1
patch_len:
  value: 8
ssm_conv:
  value: 16
ssm_rank:
  value: 8
stat_size:
  value: 64
stride:
  value: 1
transformer_layers:
  value: 4
