wandb_version: 1

attention_sparsity_factor:
  value: 2
batch_size:
  value: 128
dropout:
  value: 0.5
expanded_dim:
  value: 1
hidden_dim:
  value: 64
kernel_size:
  value: 9
lr:
  value: 0.001
max_delta:
  value: 4
max_gradient_norm:
  value: 100
num_heads:
  value: 1
patch_len:
  value: 16
ssm_conv:
  value: 32
ssm_rank:
  value: 8
stat_size:
  value: 32
stride:
  value: 1
transformer_layers:
  value: 3
