wandb_version: 1

attention_sparsity_factor:
  value: 4
batch_size:
  value: 64
dropout:
  value: 0.3
expanded_dim:
  value: 2
hidden_dim:
  value: 64
kernel_size:
  value: 11
lr:
  value: 0.001
max_delta:
  value: 5
max_gradient_norm:
  value: 1
num_heads:
  value: 4
num_layers:
  value: 6
patch_len:
  value: 32
ssm_conv:
  value: 2
ssm_rank:
  value: 16
stat_size:
  value: 64
stride:
  value: 1
transformer_layers:
  value: 2
