wandb_version: 1

attention_sparsity_factor:
  value: 5
batch_size:
  value: 64
dropout:
  value: 0.3
expanded_dim:
  value: 1
hidden_dim:
  value: 128
kernel_size:
  value: 3
lr:
  value: 0.001
max_delta:
  value: 2
max_gradient_norm:
  value: 100
num_heads:
  value: 1
num_layers:
  value: 5
patch_len:
  value: 64
ssm_conv:
  value: 2
ssm_rank:
  value: 16
stat_size:
  value: 32
transformer_layers:
  value: 6
