wandb_version: 1

attention_sparsity_factor:
  value: 6
batch_size:
  value: 128
dropout:
  value: 0.4
expanded_dim:
  value: 4
hidden_dim:
  value: 64
kernel_size:
  value: 9
lr:
  value: 0.001
max_delta:
  value: 5
max_gradient_norm:
  value: 0.01
num_heads:
  value: 2
num_layers:
  value: 2
patch_len:
  value: 8
ssm_conv:
  value: 8
ssm_rank:
  value: 16
stat_size:
  value: 64
transformer_layers:
  value: 3
