wandb_version: 1

attention_sparsity_factor:
  value: 3
batch_size:
  value: 128
dropout:
  value: 0.5
expanded_dim:
  value: 2
hidden_dim:
  value: 64
kernel_size:
  value: 3
lr:
  value: 0.001
max_delta:
  value: 1
max_gradient_norm:
  value: 1
num_heads:
  value: 4
num_layers:
  value: 2
patch_len:
  value: 16
ssm_conv:
  value: 84
ssm_rank:
  value: 8
stat_size:
  value: 64
transformer_layers:
  value: 2
