wandb_version: 1

attention_sparsity_factor:
  value: 3
batch_size:
  value: 64
dropout:
  value: 0.5
expanded_dim:
  value: 8
hidden_dim:
  value: 64
kernel_size:
  value: 5
lr:
  value: 0.001
max_delta:
  value: 3
max_gradient_norm:
  value: 0.01
num_heads:
  value: 2
num_layers:
  value: 3
patch_len:
  value: 64
ssm_conv:
  value: 84
ssm_rank:
  value: 16
stat_size:
  value: 64
transformer_layers:
  value: 5
