wandb_version: 1

attention_sparsity_factor:
  value: 6
batch_size:
  value: 64
dropout:
  value: 0.5
expanded_dim:
  value: 8
hidden_dim:
  value: 128
kernel_size:
  value: 11
lr:
  value: 0.001
max_delta:
  value: 4
max_gradient_norm:
  value: 1
num_heads:
  value: 1
num_layers:
  value: 3
patch_len:
  value: 32
ssm_conv:
  value: 16
ssm_rank:
  value: 8
stat_size:
  value: 16
transformer_layers:
  value: 2
