wandb_version: 1

attention_sparsity_factor:
  value: 5
batch_size:
  value: 64
dropout:
  value: 0.5
expanded_dim:
  value: 4
hidden_dim:
  value: 128
kernel_size:
  value: 9
lr:
  value: 0.001
max_delta:
  value: 3
max_gradient_norm:
  value: 0.01
num_heads:
  value: 2
num_layers:
  value: 6
patch_len:
  value: 16
ssm_conv:
  value: 2
ssm_rank:
  value: 8
stat_size:
  value: 32
stride:
  value: 1
transformer_layers:
  value: 5
