wandb_version: 1

attention_sparsity_factor:
  value: 6
batch_size:
  value: 128
dropout:
  value: 0.5
expanded_dim:
  value: 8
hidden_dim:
  value: 64
kernel_size:
  value: 7
lr:
  value: 0.001
max_delta:
  value: 1
max_gradient_norm:
  value: 0.01
num_heads:
  value: 1
num_layers:
  value: 3
patch_len:
  value: 32
ssm_conv:
  value: 8
ssm_rank:
  value: 8
stat_size:
  value: 32
stride:
  value: 4
transformer_layers:
  value: 4
