wandb_version: 1

attention_sparsity_factor:
  value: 5
batch_size:
  value: 64
dropout:
  value: 0.5
expanded_dim:
  value: 2
hidden_dim:
  value: 128
kernel_size:
  value: 2
lr:
  value: 0.001
max_delta:
  value: 2
max_gradient_norm:
  value: 100
num_heads:
  value: 4
num_layers:
  value: 2
patch_len:
  value: 68
ssm_conv:
  value: 32
ssm_rank:
  value: 16
stat_size:
  value: 16
transformer_layers:
  value: 3
