wandb_version: 1

attention_sparsity_factor:
  value: 4
batch_size:
  value: 128
dropout:
  value: 0.3
expanded_dim:
  value: 1
hidden_dim:
  value: 64
kernel_size:
  value: 7
lr:
  value: 0.0035020847509727236
max_delta:
  value: 4
max_gradient_norm:
  value: 0.01
num_heads:
  value: 1
num_layers:
  value: 6
patch_len:
  value: 16
ssm_conv:
  value: 32
ssm_rank:
  value: 16
stat_size:
  value: 32
stride:
  value: 4
transformer_layers:
  value: 3
