wandb_version: 1

attention_sparsity_factor:
  value: 5
batch_size:
  value: 64
dropout:
  value: 0.3
expanded_dim:
  value: 2
hidden_dim:
  value: 128
kernel_size:
  value: 7
lr:
  value: 0.032997863135382347
max_delta:
  value: 4
max_gradient_norm:
  value: 100
num_heads:
  value: 4
num_layers:
  value: 2
patch_len:
  value: 24
ssm_conv:
  value: 8
ssm_rank:
  value: 16
stat_size:
  value: 16
stride:
  value: 1
transformer_layers:
  value: 6
