wandb_version: 1

attention_sparsity_factor:
  value: 2
batch_size:
  value: 64
dropout:
  value: 0.5
expanded_dim:
  value: 1
hidden_dim:
  value: 128
kernel_size:
  value: 7
lr:
  value: 0.001
max_delta:
  value: 2
max_gradient_norm:
  value: 0.01
num_heads:
  value: 2
num_layers:
  value: 6
patch_len:
  value: 68
ssm_conv:
  value: 84
ssm_rank:
  value: 8
stat_size:
  value: 32
transformer_layers:
  value: 2
