wandb_version: 1

attention_sparsity_factor:
  value: 4
batch_size:
  value: 128
dropout:
  value: 0.4
expanded_dim:
  value: 4
hidden_dim:
  value: 64
kernel_size:
  value: 11
lr:
  value: 0.001
max_delta:
  value: 3
max_gradient_norm:
  value: 0.01
num_heads:
  value: 2
num_layers:
  value: 6
patch_len:
  value: 32
ssm_conv:
  value: 2
ssm_rank:
  value: 32
stat_size:
  value: 16
transformer_layers:
  value: 6
