wandb_version: 1

attention_sparsity_factor:
  value: 5
batch_size:
  value: 64
dropout:
  value: 0.3
expanded_dim:
  value: 4
hidden_dim:
  value: 128
kernel_size:
  value: 11
lr:
  value: 0.001
max_delta:
  value: 3
max_gradient_norm:
  value: 0.01
num_heads:
  value: 2
num_layers:
  value: 2
patch_len:
  value: 16
ssm_conv:
  value: 16
ssm_rank:
  value: 8
stat_size:
  value: 64
transformer_layers:
  value: 2
