wandb_version: 1

attention_sparsity_factor:
  value: 2
batch_size:
  value: 128
dropout:
  value: 0.5
expanded_dim:
  value: 8
hidden_dim:
  value: 128
kernel_size:
  value: 2
lr:
  value: 0.001
max_delta:
  value: 1
max_gradient_norm:
  value: 100
num_heads:
  value: 1
num_layers:
  value: 6
patch_len:
  value: 64
ssm_conv:
  value: 2
ssm_rank:
  value: 32
stat_size:
  value: 16
transformer_layers:
  value: 2
