wandb_version: 1

attention_sparsity_factor:
  value: 2
batch_size:
  value: 64
dropout:
  value: 0.4
expanded_dim:
  value: 2
hidden_dim:
  value: 64
kernel_size:
  value: 11
lr:
  value: 0.001
max_delta:
  value: 5
max_gradient_norm:
  value: 100
num_heads:
  value: 2
num_layers:
  value: 3
patch_len:
  value: 64
ssm_conv:
  value: 84
ssm_rank:
  value: 32
stat_size:
  value: 16
transformer_layers:
  value: 4
