wandb_version: 1

attention_sparsity_factor:
  value: 6
batch_size:
  value: 64
dropout:
  value: 0.4
expanded_dim:
  value: 2
hidden_dim:
  value: 256
kernel_size:
  value: 5
lr:
  value: 0.07175004115202567
max_delta:
  value: 3
max_gradient_norm:
  value: 0.01
num_heads:
  value: 4
num_layers:
  value: 3
patch_len:
  value: 32
ssm_conv:
  value: 84
ssm_rank:
  value: 16
stat_size:
  value: 64
stride:
  value: 1
transformer_layers:
  value: 4
