wandb_version: 1

attention_sparsity_factor:
  value: 5
batch_size:
  value: 128
dropout:
  value: 0.4
expanded_dim:
  value: 1
hidden_dim:
  value: 64
kernel_size:
  value: 9
lr:
  value: 0.001
max_delta:
  value: 2
max_gradient_norm:
  value: 1
num_heads:
  value: 4
num_layers:
  value: 2
patch_len:
  value: 32
ssm_conv:
  value: 84
ssm_rank:
  value: 8
stat_size:
  value: 64
transformer_layers:
  value: 4
