wandb_version: 1

attention_sparsity_factor:
  value: 6
batch_size:
  value: 128
dropout:
  value: 0.5
expanded_dim:
  value: 8
hidden_dim:
  value: 128
kernel_size:
  value: 3
lr:
  value: 0.001
max_delta:
  value: 1
max_gradient_norm:
  value: 1
num_heads:
  value: 2
num_layers:
  value: 6
patch_len:
  value: 68
ssm_conv:
  value: 84
ssm_rank:
  value: 16
stat_size:
  value: 16
transformer_layers:
  value: 3
