wandb_version: 1

attention_sparsity_factor:
  value: 4
batch_size:
  value: 64
dropout:
  value: 0.3
expanded_dim:
  value: 8
hidden_dim:
  value: 64
kernel_size:
  value: 2
lr:
  value: 0.001
max_delta:
  value: 2
max_gradient_norm:
  value: 100
num_heads:
  value: 1
num_layers:
  value: 2
patch_len:
  value: 16
ssm_conv:
  value: 16
ssm_rank:
  value: 16
stat_size:
  value: 16
transformer_layers:
  value: 6
