wandb_version: 1

attention_sparsity_factor:
  value: 2
batch_size:
  value: 64
dropout:
  value: 0.5
expanded_dim:
  value: 4
hidden_dim:
  value: 64
kernel_size:
  value: 5
lr:
  value: 0.02528165305675659
max_delta:
  value: 4
max_gradient_norm:
  value: 0.01
num_heads:
  value: 1
num_layers:
  value: 2
patch_len:
  value: 24
ssm_conv:
  value: 2
ssm_rank:
  value: 32
stat_size:
  value: 32
stride:
  value: 8
transformer_layers:
  value: 6
