wandb_version: 1

attention_sparsity_factor:
  value: 6
batch_size:
  value: 64
dropout:
  value: 0.3
expanded_dim:
  value: 2
hidden_dim:
  value: 128
kernel_size:
  value: 5
lr:
  value: 0.011476595015541729
max_delta:
  value: 5
max_gradient_norm:
  value: 0.01
num_heads:
  value: 1
num_layers:
  value: 2
patch_len:
  value: 16
ssm_conv:
  value: 2
ssm_rank:
  value: 8
stat_size:
  value: 16
stride:
  value: 4
transformer_layers:
  value: 6
