wandb_version: 1

attention_sparsity_factor:
  value: 2
batch_size:
  value: 64
dropout:
  value: 0.4
expanded_dim:
  value: 1
hidden_dim:
  value: 64
kernel_size:
  value: 2
lr:
  value: 0.010980782503190848
max_delta:
  value: 2
max_gradient_norm:
  value: 0.01
num_heads:
  value: 1
num_layers:
  value: 6
patch_len:
  value: 8
ssm_conv:
  value: 32
ssm_rank:
  value: 8
stat_size:
  value: 16
stride:
  value: 4
transformer_layers:
  value: 2
