wandb_version: 1

attention_sparsity_factor:
  value: 3
batch_size:
  value: 64
dropout:
  value: 0.3
expanded_dim:
  value: 8
hidden_dim:
  value: 64
kernel_size:
  value: 9
lr:
  value: 0.02076230430586964
max_delta:
  value: 1
max_gradient_norm:
  value: 1
num_heads:
  value: 1
num_layers:
  value: 6
patch_len:
  value: 32
ssm_conv:
  value: 8
ssm_rank:
  value: 8
stat_size:
  value: 32
stride:
  value: 8
transformer_layers:
  value: 5
