wandb_version: 1

attention_sparsity_factor:
  value: 2
batch_size:
  value: 128
dropout:
  value: 0.5
expanded_dim:
  value: 4
hidden_dim:
  value: 256
kernel_size:
  value: 9
lr:
  value: 0.008351298560408128
max_delta:
  value: 5
max_gradient_norm:
  value: 100
num_heads:
  value: 4
num_layers:
  value: 6
patch_len:
  value: 32
ssm_conv:
  value: 2
ssm_rank:
  value: 8
stat_size:
  value: 32
stride:
  value: 4
transformer_layers:
  value: 3
