wandb_version: 1

attention_sparsity_factor:
  value: 4
batch_size:
  value: 128
dropout:
  value: 0.4
expanded_dim:
  value: 8
hidden_dim:
  value: 256
kernel_size:
  value: 3
lr:
  value: 0.00815449478489222
max_delta:
  value: 1
max_gradient_norm:
  value: 1
num_heads:
  value: 2
num_layers:
  value: 3
patch_len:
  value: 16
ssm_conv:
  value: 8
ssm_rank:
  value: 8
stat_size:
  value: 32
stride:
  value: 8
transformer_layers:
  value: 3
