wandb_version: 1

attention_sparsity_factor:
  value: 2
batch_size:
  value: 128
dropout:
  value: 0.4
expanded_dim:
  value: 8
hidden_dim:
  value: 64
kernel_size:
  value: 11
lr:
  value: 0.05997786308931897
max_delta:
  value: 1
max_gradient_norm:
  value: 0.01
num_heads:
  value: 2
num_layers:
  value: 3
patch_len:
  value: 32
ssm_conv:
  value: 32
ssm_rank:
  value: 16
stat_size:
  value: 16
stride:
  value: 8
transformer_layers:
  value: 4
