wandb_version: 1

attention_sparsity_factor:
  value: 3
batch_size:
  value: 64
dropout:
  value: 0.4
expanded_dim:
  value: 2
hidden_dim:
  value: 256
kernel_size:
  value: 5
lr:
  value: 0.07576531965737693
max_delta:
  value: 2
max_gradient_norm:
  value: 100
num_heads:
  value: 2
num_layers:
  value: 3
patch_len:
  value: 32
ssm_conv:
  value: 32
ssm_rank:
  value: 32
stat_size:
  value: 32
stride:
  value: 1
transformer_layers:
  value: 3
