wandb_version: 1

attention_sparsity_factor:
  value: 6
batch_size:
  value: 128
dropout:
  value: 0.4
expanded_dim:
  value: 2
hidden_dim:
  value: 256
kernel_size:
  value: 9
lr:
  value: 0.024287640384092406
max_delta:
  value: 5
max_gradient_norm:
  value: 100
num_heads:
  value: 4
num_layers:
  value: 5
patch_len:
  value: 32
ssm_conv:
  value: 16
ssm_rank:
  value: 16
stat_size:
  value: 32
stride:
  value: 16
transformer_layers:
  value: 2
