wandb_version: 1

attention_sparsity_factor:
  value: 4
batch_size:
  value: 128
dropout:
  value: 0.3
expanded_dim:
  value: 8
hidden_dim:
  value: 64
kernel_size:
  value: 11
lr:
  value: 0.055068745931178914
max_delta:
  value: 5
max_gradient_norm:
  value: 100
num_heads:
  value: 4
num_layers:
  value: 5
patch_len:
  value: 8
ssm_conv:
  value: 32
ssm_rank:
  value: 8
stat_size:
  value: 64
stride:
  value: 4
transformer_layers:
  value: 5
