wandb_version: 1

attention_sparsity_factor:
  value: 5
batch_size:
  value: 128
dropout:
  value: 0.4
expanded_dim:
  value: 4
hidden_dim:
  value: 64
kernel_size:
  value: 2
lr:
  value: 0.0892354782872995
max_delta:
  value: 5
max_gradient_norm:
  value: 100
num_heads:
  value: 1
num_layers:
  value: 2
patch_len:
  value: 8
ssm_conv:
  value: 2
ssm_rank:
  value: 8
stat_size:
  value: 32
stride:
  value: 16
transformer_layers:
  value: 4
