wandb_version: 1

attention_sparsity_factor:
  value: 6
batch_size:
  value: 128
dropout:
  value: 0.4
expanded_dim:
  value: 8
hidden_dim:
  value: 64
kernel_size:
  value: 2
lr:
  value: 0.045839174938843534
max_delta:
  value: 3
max_gradient_norm:
  value: 1
num_heads:
  value: 2
num_layers:
  value: 3
patch_len:
  value: 32
ssm_conv:
  value: 2
ssm_rank:
  value: 8
stat_size:
  value: 16
stride:
  value: 8
transformer_layers:
  value: 3
