wandb_version: 1

attention_sparsity_factor:
  value: 5
batch_size:
  value: 64
dropout:
  value: 0.4
expanded_dim:
  value: 4
hidden_dim:
  value: 256
kernel_size:
  value: 5
lr:
  value: 0.034449845489554445
max_delta:
  value: 1
max_gradient_norm:
  value: 1
num_heads:
  value: 2
num_layers:
  value: 2
patch_len:
  value: 8
ssm_conv:
  value: 2
ssm_rank:
  value: 32
stat_size:
  value: 64
stride:
  value: 4
transformer_layers:
  value: 6
