wandb_version: 1

attention_sparsity_factor:
  value: 4
batch_size:
  value: 128
dropout:
  value: 0.5
expanded_dim:
  value: 4
hidden_dim:
  value: 256
kernel_size:
  value: 3
lr:
  value: 0.08211373833249165
max_delta:
  value: 2
max_gradient_norm:
  value: 100
num_heads:
  value: 4
num_layers:
  value: 3
patch_len:
  value: 16
ssm_conv:
  value: 32
ssm_rank:
  value: 8
stat_size:
  value: 16
stride:
  value: 8
transformer_layers:
  value: 2
