wandb_version: 1

attention_sparsity_factor:
  value: 2
batch_size:
  value: 128
dropout:
  value: 0.5
expanded_dim:
  value: 8
hidden_dim:
  value: 64
kernel_size:
  value: 5
lr:
  value: 0.07901375070297768
max_delta:
  value: 5
max_gradient_norm:
  value: 0.01
num_heads:
  value: 2
num_layers:
  value: 2
patch_len:
  value: 16
ssm_conv:
  value: 16
ssm_rank:
  value: 8
stat_size:
  value: 32
stride:
  value: 8
transformer_layers:
  value: 6
