wandb_version: 1

attention_sparsity_factor:
  value: 6
batch_size:
  value: 64
dropout:
  value: 0.5
expanded_dim:
  value: 4
hidden_dim:
  value: 128
kernel_size:
  value: 7
lr:
  value: 0.003058829933346201
max_delta:
  value: 3
max_gradient_norm:
  value: 1
num_heads:
  value: 1
num_layers:
  value: 3
patch_len:
  value: 32
ssm_conv:
  value: 8
ssm_rank:
  value: 32
stat_size:
  value: 32
stride:
  value: 8
transformer_layers:
  value: 3
