wandb_version: 1

attention_sparsity_factor:
  value: 2
batch_size:
  value: 64
dropout:
  value: 0.3
expanded_dim:
  value: 4
hidden_dim:
  value: 128
kernel_size:
  value: 2
lr:
  value: 0.030718139084821832
max_delta:
  value: 5
max_gradient_norm:
  value: 100
num_heads:
  value: 1
num_layers:
  value: 6
patch_len:
  value: 32
ssm_conv:
  value: 84
ssm_rank:
  value: 32
stat_size:
  value: 64
stride:
  value: 1
transformer_layers:
  value: 3
