wandb_version: 1

attention_sparsity_factor:
  value: 2
batch_size:
  value: 64
dropout:
  value: 0.5
expanded_dim:
  value: 8
hidden_dim:
  value: 64
kernel_size:
  value: 9
lr:
  value: 0.0011042983317296753
max_delta:
  value: 2
max_gradient_norm:
  value: 0.01
num_heads:
  value: 1
num_layers:
  value: 5
patch_len:
  value: 16
ssm_conv:
  value: 2
ssm_rank:
  value: 32
stat_size:
  value: 64
stride:
  value: 8
transformer_layers:
  value: 5
