wandb_version: 1

attention_sparsity_factor:
  value: 6
batch_size:
  value: 64
dropout:
  value: 0.3
expanded_dim:
  value: 8
hidden_dim:
  value: 64
kernel_size:
  value: 2
lr:
  value: 0.06637820555888607
max_delta:
  value: 1
max_gradient_norm:
  value: 1
num_heads:
  value: 2
num_layers:
  value: 6
patch_len:
  value: 16
ssm_conv:
  value: 84
ssm_rank:
  value: 16
stat_size:
  value: 32
stride:
  value: 4
transformer_layers:
  value: 5
