wandb_version: 1

attention_sparsity_factor:
  value: 6
batch_size:
  value: 64
dropout:
  value: 0.5
expanded_dim:
  value: 1
hidden_dim:
  value: 128
kernel_size:
  value: 7
lr:
  value: 0.001
max_delta:
  value: 3
max_gradient_norm:
  value: 1
num_heads:
  value: 4
num_layers:
  value: 2
patch_len:
  value: 64
ssm_conv:
  value: 16
ssm_rank:
  value: 32
stat_size:
  value: 32
transformer_layers:
  value: 2
