wandb_version: 1

attention_sparsity_factor:
  value: 3
batch_size:
  value: 128
dropout:
  value: 0.5
expanded_dim:
  value: 2
hidden_dim:
  value: 128
kernel_size:
  value: 11
lr:
  value: 0.001
max_delta:
  value: 4
max_gradient_norm:
  value: 1
num_heads:
  value: 2
num_layers:
  value: 6
patch_len:
  value: 64
ssm_conv:
  value: 2
ssm_rank:
  value: 16
stat_size:
  value: 64
transformer_layers:
  value: 2
