wandb_version: 1

attention_sparsity_factor:
  value: 3
batch_size:
  value: 64
dropout:
  value: 0.4
expanded_dim:
  value: 2
hidden_dim:
  value: 128
kernel_size:
  value: 9
lr:
  value: 0.001
max_delta:
  value: 3
max_gradient_norm:
  value: 0.01
num_heads:
  value: 4
num_layers:
  value: 3
patch_len:
  value: 8
ssm_conv:
  value: 16
ssm_rank:
  value: 32
stat_size:
  value: 64
transformer_layers:
  value: 2
