wandb_version: 1

attention_sparsity_factor:
  value: 3
batch_size:
  value: 64
dropout:
  value: 0.4
expanded_dim:
  value: 8
hidden_dim:
  value: 64
kernel_size:
  value: 7
lr:
  value: 0.001
max_delta:
  value: 5
max_gradient_norm:
  value: 100
num_heads:
  value: 2
num_layers:
  value: 6
patch_len:
  value: 64
ssm_conv:
  value: 2
ssm_rank:
  value: 8
stat_size:
  value: 16
transformer_layers:
  value: 6
