wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.4
hidden_dim:
  value: 128
kernel_size:
  value: 3
lr:
  value: 0.001
max_gradient_norm:
  value: 100
num_heads:
  value: 2
patch_len:
  value: 32
stride:
  value: 2
transformer_layers:
  value: 3
