wandb_version: 1

attention_sparsity_factor:
  value: 3
batch_size:
  value: 64
dropout:
  value: 0.3
expanded_dim:
  value: 4
hidden_dim:
  value: 64
kernel_size:
  value: 3
lr:
  value: 0.001
max_delta:
  value: 4
max_gradient_norm:
  value: 100
num_heads:
  value: 1
num_layers:
  value: 5
patch_len:
  value: 32
ssm_conv:
  value: 32
ssm_rank:
  value: 32
stat_size:
  value: 16
transformer_layers:
  value: 5
