wandb_version: 1

attention_sparsity_factor:
  value: 4
batch_size:
  value: 128
dropout:
  value: 0.3
expanded_dim:
  value: 8
hidden_dim:
  value: 64
kernel_size:
  value: 2
lr:
  value: 0.001
max_delta:
  value: 3
max_gradient_norm:
  value: 100
num_heads:
  value: 1
num_layers:
  value: 3
patch_len:
  value: 16
ssm_conv:
  value: 16
ssm_rank:
  value: 32
stat_size:
  value: 32
transformer_layers:
  value: 2
