wandb_version: 1

attention_sparsity_factor:
  value: 6
batch_size:
  value: 64
dropout:
  value: 0.3
expanded_dim:
  value: 1
hidden_dim:
  value: 64
kernel_size:
  value: 5
lr:
  value: 0.001
max_delta:
  value: 3
max_gradient_norm:
  value: 100
num_heads:
  value: 2
num_layers:
  value: 3
patch_len:
  value: 16
ssm_conv:
  value: 2
ssm_rank:
  value: 16
stat_size:
  value: 64
transformer_layers:
  value: 6
