wandb_version: 1

attention_sparsity_factor:
  value: 5
batch_size:
  value: 128
dropout:
  value: 0.5
expanded_dim:
  value: 8
hidden_dim:
  value: 64
kernel_size:
  value: 5
lr:
  value: 0.001
max_delta:
  value: 1
max_gradient_norm:
  value: 100
num_heads:
  value: 4
num_layers:
  value: 6
patch_len:
  value: 64
ssm_conv:
  value: 84
ssm_rank:
  value: 32
stat_size:
  value: 32
transformer_layers:
  value: 2
