wandb_version: 1

attention_sparsity_factor:
  value: 4
batch_size:
  value: 128
dropout:
  value: 0.4
expanded_dim:
  value: 1
hidden_dim:
  value: 64
kernel_size:
  value: 2
lr:
  value: 0.001
max_delta:
  value: 2
max_gradient_norm:
  value: 0.01
num_heads:
  value: 4
num_layers:
  value: 6
patch_len:
  value: 16
ssm_conv:
  value: 8
ssm_rank:
  value: 32
stat_size:
  value: 32
transformer_layers:
  value: 5
