wandb_version: 1

attention_sparsity_factor:
  value: 6
batch_size:
  value: 128
dropout:
  value: 0.5
expanded_dim:
  value: 4
hidden_dim:
  value: 128
kernel_size:
  value: 2
lr:
  value: 0.001
max_delta:
  value: 5
max_gradient_norm:
  value: 0.01
num_heads:
  value: 1
num_layers:
  value: 5
patch_len:
  value: 24
ssm_conv:
  value: 2
ssm_rank:
  value: 16
stat_size:
  value: 64
transformer_layers:
  value: 4
