wandb_version: 1

attention_sparsity_factor:
  value: 3
batch_size:
  value: 64
dropout:
  value: 0.4
expanded_dim:
  value: 1
hidden_dim:
  value: 64
kernel_size:
  value: 2
lr:
  value: 0.001
max_delta:
  value: 2
max_gradient_norm:
  value: 1
num_heads:
  value: 2
num_layers:
  value: 5
patch_len:
  value: 8
ssm_conv:
  value: 8
ssm_rank:
  value: 16
stat_size:
  value: 64
transformer_layers:
  value: 3
