wandb_version: 1

attention_sparsity_factor:
  value: 3
batch_size:
  value: 128
dropout:
  value: 0.3
expanded_dim:
  value: 1
hidden_dim:
  value: 64
kernel_size:
  value: 2
lr:
  value: 0.001
max_delta:
  value: 4
max_gradient_norm:
  value: 0.01
num_heads:
  value: 2
num_layers:
  value: 3
patch_len:
  value: 32
ssm_conv:
  value: 2
ssm_rank:
  value: 8
stat_size:
  value: 16
transformer_layers:
  value: 6
