wandb_version: 1

attention_sparsity_factor:
  value: 6
batch_size:
  value: 128
dropout:
  value: 0.3
expanded_dim:
  value: 4
hidden_dim:
  value: 64
kernel_size:
  value: 11
lr:
  value: 0.001
max_delta:
  value: 4
max_gradient_norm:
  value: 100
num_heads:
  value: 4
num_layers:
  value: 6
patch_len:
  value: 24
ssm_conv:
  value: 84
ssm_rank:
  value: 32
stat_size:
  value: 32
transformer_layers:
  value: 2
