wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.3
hidden_dim:
  value: 64
kernel_size:
  value: 11
lr:
  value: 0.001
max_gradient_norm:
  value: 100
num_heads:
  value: 2
patch_len:
  value: 32
stride:
  value: 8
transformer_layers:
  value: 3
